# Generated by Django 4.2.6 on 2024-01-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverbanksda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritualBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='books/')),
            ],
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
