# Generated by Django 5.0.1 on 2024-01-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverbanksda', '0002_spiritualbook_delete_documents_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritualbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='spiritualbook',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spiritualbook',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
